### PR TITLE
Change weapon sway from global motion to local

### PR DESCRIPTION
**Pull request by bramreth**
(This kit is bonkers cool 😍 )

When turning the camera left or right, the weapon sway was fixed in a global direction, so when moving forwards and back while looking in the +x direction, the weapon would sway left and right.

Beefed it out and multiplying by the inverse of the player's basis turns that global force into a local direction, so the weapon sway rotates with the player ^^

### CODE REVIEW

**Comment by bramreth** [comment]
Here's a video highlighting the old behaviour, after turning right, the gun starts moving left and right instead of forward and back:

https://github.com/KenneyNL/Starter-Kit-FPS/assets/23744598/cee0893a-3561-4252-91d7-50f9f5e5f4fd

**Comment by KenneyNL** [comment]
This has been merged by hand, thank you! Great change :)

**Comment by bramreth** [comment]
(Just in case it got lost at some point, I don't see the basis.inverse() change in main or the last few commits - it looks like you're on top of lots of patches right now so just a reminder if this line still needs to go in 💞)

**Comment by KenneyNL** [comment]
You're right! It got removed again somewhere down the line, sorry about that - it's back in!

**Pull request closed without merging**
